@userId = 6678067e5cd779df11cd6512

### Get all user
GET http://{{address}}:{{port}}/api/v1/user

### Get user by id
GET http://{{address}}:{{port}}/api/v1/user/{{userId}}

### Create new user
POST http://{{address}}:{{port}}/api/v1/user
Content-Type: application/json

{
  "firstName": "Slava",
  "lastName": "Mashkov",
  "email": "mashkov.vd@gmail.com",
  "password": "test123"
}

### Update user by id
PUT http://{{address}}:{{port}}/api/v1/user/{{userId}}
Content-Type: application/json

{
  "firstName": "Dima",
  "password": "test345"
}

### Delete user by id
DELETE http://{{address}}:{{port}}/api/v1/user/{{userId}}

